CREATE TABLE IF NOT EXISTS planejamento (
  id INT PRIMARY KEY AUTO_INCREMENT,
  serie VARCHAR(10) NOT NULL,
  TURMA VARCHAR(10) NOT NULL,
  data DATE NOT NULL,
  tema VARCHAR(1000) NOT NULL,
  objetivos VARCHAR(1000) NOT NULL,
  area_conhecimento VARCHAR(1000) NOT NULL,
  disciplina VARCHAR(1000) NOT NULL,
  competencias_ger VARCHAR(1000) NOT NULL,
  competencias_esp VARCHAR(1000) NOT NULL,
  habilidades VARCHAR(1000) NOT NULL,
  objetos VARCHAR(1000) NOT NULL,
  descricao VARCHAR(1000) NOT NULL,
  recursos VARCHAR(1000) NOT NULL,
  avaliacao VARCHAR(1000) NOT NULL
  )
